### PR TITLE
Added authentication with JWT

### PR DESCRIPTION
**Pull request by anag004**
- Instead of a base API for queries modified to use mongoose queries directly in the exposed APIs - provides greater flexibility.
- Added login and authentication functionality with JWT. We can now login using password and username at the `/users/login` endpoint.
- For demonstration purposes, made viewing all events a privileged action.

TODO:
- Make logout functionality
- Different levels of access to API functions (admin, normal user etc)
- Hash passwords while storing

### CODE REVIEW

**Comment by Atishya-jain** [comment]
Screenshot from 2019-07-05 23-32-10

I get this error if I make any request that is unauthorized or not defined.
I also got this error when I tried to login using /api/user/login and setting: username=Ananye and password=1234
Look into this

**Comment by Atishya-jain** [comment]
Screenshot from 2019-07-05 23-59-31
I got this error when I made a get request instead of post on /api/user/login

Correct this

**Comment by Atishya-jain** [comment]
Screenshot from 2019-07-05 23-31-58
I got this error on trying to create duplicate entries in the table. Duplicates cannot be created due to unique keys. You should properly return a message saying user already exists or something.
The entire App shouldn't crash.

Look into this too.
I am closing this pull request. Correct these errors and raise it once again

**Comment by anag004** [comment]
> Screenshot from 2019-07-05 23-59-31
> I got this error when I made a get request instead of post on /api/user/login
> 
> Correct this

So, this error is just because the get request enters the `router.get('/:id', get)` and `login` is not a valid id. Since we don't plan on exposing this API anyway, this shouldn't be a problem.

**Comment by anag004** [comment]
> Screenshot from 2019-07-05 23-32-10
> 
> I get this error if I make any request that is unauthorized or not defined.
> I also got this error when I tried to login using /api/user/login and setting: username=Ananye and password=1234
> Look into this

I was not able to replicate the error. POSTing at `/user/login` with `username: AnanyeAgarwal` and `password:12345` gives:

```
<html>
    <head>
        <meta charset='utf-8'>
        <title>Not found: User with username AnanyeAgarwal does not exist</title>
        <style>* {
  margin: 0;
...
```

POSTing with username=Ananye and password=1234 gives a valid token

```
{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiQW5hbnllIiwiaWF0IjoxNTYyNDIwMzk5LCJleHAiOjE1NjI1OTMxOTksImlzcyI6ImRldmNsdWItY3RmIn0.AyoxotEr8iOhawUbBsvIUBwfgMMpvcHdT4ZjThO4fiU",
    "status": 200,
    "result": {
...
```

POSTing with username Ananye and password 12345 gives

```
<html>
    <head>
        <meta charset='utf-8'>
        <title>Incorrect login: User with username Ananye does not exist or incorrect password entered</title>
        <style>* {
  margin: 0;
  padding: 0;
  outline: 0;
...
```

The app does not crash.

**Comment by anag004** [comment]
> Screenshot from 2019-07-05 23-31-58
> I got this error on trying to create duplicate entries in the table. Duplicates cannot be created due to unique keys. You should properly return a message saying user already exists or something.
> The entire App shouldn't crash.
> 
> Look into this too.
> I am closing this pull request. Correct these errors and raise it once again

This is because you're using the `/dummy` API which uses the `createDummyData` function. This function does not have proper error handling in it and hence crashes. The `create` function in `crudFactory` works properly. For example, if I POST at '/user/' the following data of a user which already exists:

```
 {
            "entryNumber": "2017CS1XXXX",
            "hostel": "XXXX",
            "gender": "female",
            "rating": 5,
            "isAdmin": 0,
            "events": [],
            "problems": [],
            "participant": [],
            "_id": "5d0bc9d7c0705976f8439caf",
            "username": "Ananye",
            "password": "1234",
            "name": "Ananye Agarwal",
            "email": "ananye@gmail.com",
            "institution": "IIT DELHI"
}
```

I will get the error message:

```
...
}
</style>
    </head>
    <body>
        <div id="wrapper">
            <h1>Connect</h1>
            <h2>
                <em>500</em> MongoError: E11000 duplicate key error collection: local.users index: _id_ dup key: { : ObjectId(&#39;5d0bc9d7c0705976f8439caf&#39;) }
            </h2>
            <ul id="stacktrace">
...
```

The app does not crash. Further, since we are only using the `/dummy/` api for testing, I don't think this will matter much.

**Comment by Atishya-jain** [comment]
Screenshot from 2019-07-07 01-22-15
I agree with the above points.
Just check this too for once.

Look at the Request in the image intercepted and explain me the reason for this error?
Maybe I am sending some wrong request

**Comment by anag004** [comment]
> Screenshot from 2019-07-07 01-22-15
> I agree with the above points.
> Just check this too for once.
> 
> Look at the Request in the image intercepted and explain me the reason for this error?
> Maybe I am sending some wrong request

Try sending this request again but this time add the variable `JWT_SECRET` to your `.env` file. For example, I have `JWT_SECRET=addjsonwebtokensecretherelikeQuiscustodietipsoscustodes`.

**Pull request closed without merging**
